name: Docker

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: package docker
      run: |
        VERSION=$(date +%s)
        USERNAME=mmlogin
        REPOSLUG=learn-github-actions

        docker login docker.pkg.github.com --username ${USERNAME} --password ${{ secrets.GITHUB_TOKEN }}
        docker build . --file Dockerfile --tag docker.pkg.github.com/${USERNAME}/${REPOSLUG}/app:${VERSION}
        docker push docker.pkg.github.com/${USERNAME}/${REPOSLUG}/app:${VERSION}
      env:
        CI: true
